### ISSUE TITLE
Lost data migrating from InfluxDB v1 to v2

### ISSUE THREAD

**Issue by rayxxxxx** [danieloldberg/addon-influxdbv2#10] opened 2023-10-15 21:09 UTC
Hi,
I followed the steps to migrate from InfluxDB v1 to InfluxDB v2, as described as in the FAQ "Migrating from InfluxDB v1 to v2", and I didn't catch any error.
The issue is that in InfluxDB v2 I've got just 3 days of data and I lost the older (my homeassistant bucket doesn't have retention policy). Why? How can I solve?

Thks

**Comment by MarAlze** [comment] 2024-01-30 12:45
The problem is in the following line during the migration


influx_inspect export -database homeassistant -retention autogen -out /data/exports/influxdb -lponly -datadir _**/data/influxb**_ -waldir /data/influxdb/wal # Export the influxdb timeseries data


Change it like this:


influx_inspect export -database homeassistant -retention autogen -out /data/exports/influxdb -lponly -datadir _**/data/influxdb/data**_ -waldir /data/influxdb/wal # Export the influxdb timeseries data



With the first line of code, only the wal files (short-term input memory) are being exported, because the long-term data series are not being found. This is fixed in the 2nd line.

**Closed as completed** 2024-01-30 13:45 UTC
